name = "bbay-backend-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "development"

[[durable_objects.bindings]]
name = "AUCTION_ROOM"
class_name = "AuctionRoomDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AuctionRoomDO"]

[build]
command = "npm run build"
